"""Expand the grafting topic bank (injection_diverse.json) with diverse, clean
off-topic paragraphs, so the model learns "switch to something fresh" instead of
memorizing a handful of topics. Appends NEW entries to the existing file (with a
.bak backup); matches the existing schema exactly: {"items":[{"value": "..."}]}.

Run:  python scripts/expand_topic_bank.py /u/fash/babel-ai/data/injection_diverse.json
"""
import json
import shutil
import sys

NEW = [
    # --- astronomy / sky ---
    "A black hole is not a hole but a place where gravity has folded space so steeply that not even light can climb back out. The boundary, the event horizon, hides everything within behind a one-way curtain.\n\nMatter spiralling inward heats to millions of degrees and blazes in X-rays before it vanishes, so the darkest objects in the universe announce themselves with some of the brightest light we can see.",
    "A comet is a dirty snowball left over from the birth of the solar system, a few kilometres of ice and dust that spend most of their lives frozen in the dark far beyond the planets.\n\nWhen one falls close to the sun, the ice boils straight to gas and unfurls a glowing tail that always points away from the sun, pushed back by the pressure of sunlight itself, so the comet chases its own head as it rounds the star.",
    "The aurora is the solar wind made visible, a stream of charged particles from the sun caught by the earth's magnetic field and funnelled toward the poles. There they slam into the upper air and make it glow.\n\nOxygen answers in green and deep red, nitrogen in violet and blue, and the curtains ripple because they trace the invisible magnetic lines along which the particles rain down from space.",
    "Tides are the moon's grip on the ocean, a bulge of water raised on the side of the earth facing the moon and, oddly, another on the far side where inertia wins over gravity.\n\nAs the planet turns beneath these bulges most coasts see two high tides a day, and when the sun lines up with the moon their pulls combine into the great spring tides that bare the seabed and drown the marshes.",

    # --- food & drink ---
    "Roasting coffee is a controlled fire that turns a grassy green seed into something aromatic and brown. Around two hundred degrees the beans crack audibly, doubling in size as trapped water flashes to steam.\n\nA lighter roast keeps the bright, fruity acids of the origin; push further and caramelised sugars and roast smoke take over, until at the darkest end every bean tastes of the roaster rather than the farm that grew it.",
    "Aging cheese is the slow, deliberate management of decay. Bacteria and moulds break the curd's proteins and fats into hundreds of aromatic compounds, and a cave's cool damp air keeps the process from racing out of control.\n\nSome wheels are washed with brine to grow a pungent orange rind; others are pierced with needles so blue mould can breathe and spread its veins through the paste, turning fresh milk into something savoury and almost meaty.",
    "The heat of a chili pepper is a chemical bluff. Capsaicin binds to the same nerve receptor that senses scalding, so the brain reports burning where no tissue is harmed, and the body sweats and floods with endorphins in response.\n\nPlants evolved the molecule to deter mammals, whose teeth destroy the seeds, while birds feel nothing and carry the seeds away, which is why the fiercest peppers ripen a bright warning red.",
    "Kimchi is a jar of managed fermentation. Salt draws water from the cabbage and holds back rot while wild lactic bacteria, already living on the leaves, convert its sugars into tangy acid that preserves the vegetable for months.\n\nThe brine bubbles as it sours, garlic and chili deepening into something rounder, and every household's crock tastes a little different because the microbes drift in from the kitchen air and the hands that pack the jar.",
    "Chocolate begins as a bitter seed buried in the pulp of a tropical pod. The beans are heaped and left to ferment for days, and only that rot develops the precursors of flavour before they are dried and shipped.\n\nRoasting and long grinding coax out hundreds of aromas, but the final magic is tempering, coaxing the cocoa fat to crystallise in just one of its several forms so the bar snaps cleanly and melts at the warmth of the tongue.",

    # --- history & culture ---
    "The Silk Road was never a single road but a shifting web of caravan tracks and sea lanes across which silk, spices, and ideas travelled between China and the Mediterranean for over a thousand years.\n\nFew merchants made the whole journey; goods passed hand to hand through a chain of oasis cities, and along with the cargo moved paper, gunpowder, religions, and the plague, so the routes remade every civilisation they touched.",
    "Gutenberg's printing press did not invent the letter but the idea of the reusable metal letter, cast by the thousand from a hand mould so a page could be assembled, inked, and pressed hundreds of times.\n\nWithin fifty years the presses of Europe had printed more books than all the scribes of the previous millennium, and cheap identical copies made it possible for a lone monk's pamphlet to shake an entire church.",
    "Viking navigators crossed open ocean without a compass, reading the sea itself: the flight of birds, the colour of the water, the run of the swells that wrapped around unseen islands.\n\nLegend and some evidence credit them with a sunstone, a crystal that reveals the sun's position through cloud by the way it splits polarised light, letting a helmsman hold a true course under the grey skies of the North Atlantic.",
    "Egyptian embalmers turned death into a nine-week craft. They drew the brain out through the nose, dried the body for forty days in natron salt, and wrapped it in hundreds of metres of linen with charms tucked between the layers.\n\nThe organs were sealed in jars guarded by carved gods, and the whole ritual aimed to keep the body recognisable, because the soul was thought to need its old form to find its way home each night.",
    "The painters of Lascaux worked by lamplight deep underground, blowing charcoal and ochre across the rock to conjure bulls and horses that seem to gallop when a flame flickers over them.\n\nSeventeen thousand years later we still cannot say why they crawled so far from daylight to paint, but the animals are drawn with such assured motion that the caves feel less like decoration than like the first attempt to stop time.",

    # --- animals & biology ---
    "An octopus is a mind distributed through its arms. Two-thirds of its neurons lie outside the brain, so each limb can taste, grope, and decide half on its own while the animal solves a puzzle with the rest.\n\nIt can pour its boneless body through a gap the size of its eye, rewrite the colour and texture of its skin in a heartbeat to vanish against a rock, and then, after a single brief season of breeding, it dies.",
    "Beneath a forest floor runs a fungal internet, threads of mycelium finer than hair that lace through the soil and plug into the roots of nearly every tree.\n\nThrough this network trees trade sugar for the fungus's minerals and even send warnings and food to their neighbours, so a shaded seedling can be kept alive by a distant elder, and the woodland behaves less like a crowd of rivals than a single connected being.",
    "Each autumn monarch butterflies fly thousands of kilometres to a few mountain groves in Mexico that none of them has ever seen. The travellers are the great-grandchildren of the ones that left the year before.\n\nHow the memory of the destination is written into so short-lived a creature remains one of biology's puzzles; they seem to carry a sun compass in their antennae, correcting for the hour as they steer south on paper-thin wings.",
    "A giant sequoia is the largest living thing by sheer volume, a tower of soft red wood that can outlive three thousand years of storms. Its bark grows nearly a metre thick, spongy and almost fireproof.\n\nFire is in fact its ally: the heat cracks open the cones and clears the competing brush, so the seedlings sprout in sunlit ash, which is why a century of dutifully extinguishing every wildfire nearly doomed the species.",
    "A tardigrade is a half-millimetre animal that treats catastrophe as an inconvenience. Dried out, frozen near absolute zero, or flung into the vacuum of space, it curls into a desiccated husk and simply stops.\n\nIn that suspended state it can wait for decades, replacing the water in its cells with a glassy sugar that props up its machinery, and then, given a single drop of water, it swells, unfolds, and lumbers off as if nothing happened.",
    "The salmon's life is a single enormous round trip. Hatched in a cold gravel stream, it drifts to the sea and grows for years in salt water before the urge to breed drags it back to the exact river of its birth.\n\nIt navigates home partly by smell, remembering the chemical signature of its natal creek, then fights upstream against current and waterfall, its body decaying as it goes, to spawn once in the shallows and die.",
    "Whale song travels because the deep ocean is built to carry it. A layer of cold water traps low sound and channels it for hundreds of kilometres, so a humpback's moans and rising cries can reach a listener an ocean away.\n\nThe males of a population all sing the same elaborate song and slowly revise it together over the years, a shared composition that drifts and changes like a fashion passed between animals that may never meet.",
    "Spider silk is spun as a liquid protein and hardens into a thread that, weight for weight, outperforms steel and rivals the toughness of Kevlar. A single spider makes several kinds for different jobs.\n\nThe dragline that saves it from a fall is stiff and strong; the spiral that catches prey is stretchy and glued with droplets; and the whole web is a tuned instrument the spider reads through its legs, feeling the twang of a trapped fly.",

    # --- earth & weather ---
    "The monsoon is a season that breathes. In summer the land heats faster than the sea, and the rising warm air pulls in a moist ocean wind that dumps months of rain on half a continent in a few weeks.\n\nEntire civilisations time their year to its arrival; a late or feeble monsoon means failed harvests and empty reservoirs, while too violent a one drowns the fields, so a billion people watch the sky for the first grey clouds.",
    "Earthquakes are the earth releasing stress that has built for centuries. The rigid plates of the crust grind past one another, snagging along a fault until the rock can bend no further and snaps, lurching metres in seconds.\n\nThe rupture radiates as waves that shake the ground, and it is rarely the shaking alone that kills but the buildings it topples, which is why engineers hang tall towers on rollers and dampers to let them sway instead of shatter.",
    "A geyser is plumbing on a knife-edge. Groundwater seeps into a narrow channel over a hot magma chamber, and the weight of the column above lets the deep water superheat past boiling without erupting.\n\nEventually a little steam forms, lifts some water out, and drops the pressure below, so the whole superheated column flashes to steam at once and rockets skyward, then the plumbing refills and the countdown to the next eruption quietly begins.",
    "The great chambers of a limestone cave are carved by nothing more violent than slightly acidic rain, which dissolves the rock grain by grain over hundreds of thousands of years.\n\nWhere the mineral-laden water drips from a ceiling it leaves a trace of stone behind, and stalactites grow down and stalagmites up at the pace of a hair a year, until in the oldest caverns they meet in columns that took an ice age to build.",

    # --- crafts & arts ---
    "A great violin is a puzzle of dead wood that somehow sings. The maker carves a spruce top and maple back to a thickness judged by tapping and flexing, tuning the plates by ear before the box is even closed.\n\nThe varnish, the curl of the scroll, the exact arch of the belly all shape the tone, and centuries after Stradivari no one can fully say why his instruments carry a hall, which keeps the craft half science and half stubborn faith.",
    "Ballet hides brutal effort behind the appearance of weightlessness. A dancer on pointe balances her whole body on a few square centimetres of blocked satin, holding a line that took a decade of daily class to make look easy.\n\nThe vocabulary is a frozen French dictionary of steps, each with a name and a right way, yet the aim of all that discipline is the illusion that the body has escaped gravity and moves only because the music asks it to.",
    "Chinese calligraphy treats a written character as a living gesture, not a shape to be copied. The brush is soft and answers to the slightest change of pressure, angle, and speed, recording the writer's breath in ink.\n\nA stroke must be made once and cannot be retouched, so years go into learning to load the brush and commit, and connoisseurs read a scroll less for its words than for the confidence and rhythm of the hand that left them.",
    "Glassblowing is a race against cooling. Gathered from the furnace as a glowing honey-thick blob on the end of a steel pipe, the glass must be shaped while it is soft, kept turning constantly so gravity does not pull it into a droop.\n\nThe blower breathes a bubble into the mass and coaxes it with wet wood and wet paper, reheating again and again, working in the narrow window between too molten to hold a shape and too stiff to move at all.",
    "Kintsugi mends broken pottery with lacquer dusted in gold, treating the fracture as part of the object's history rather than a flaw to disguise. The gold seams trace exactly where the bowl once fell.\n\nThe philosophy behind it prizes the marks of age and accident, so a repaired cup can be valued more than the unbroken original, a quiet argument that things, and perhaps people, are made more beautiful by surviving their damage.",
    "Origami turns a single square of paper, uncut and unglued, into cranes, boxes, and beasts through nothing but folding. Every crease is a hinge, and the finished form is locked by the geometry of the paper itself.\n\nModern masters use mathematics to design fantastically complex models, and the same fold patterns that shape a paper insect now help engineers pack a telescope's mirror or a car's airbag into a space far smaller than it will fill.",

    # --- sport & skill ---
    "Free diving is the art of doing nothing, gracefully, on a single breath. Divers slow their hearts, flood their minds with calm, and sink past the point where the lungs compress to the size of fists.\n\nA reflex shared with seals shunts blood to the core and drops the pulse to a crawl, letting trained divers reach a hundred metres and back on one lungful, in a silent blue dark where panic is the only real enemy.",
    "Surfing is a brief negotiation with a wave that has travelled thousands of kilometres to break. Swells born under distant storms fan out across the ocean and only rear up and curl where the seabed suddenly shallows.\n\nThe surfer paddles to match the wave's speed at the instant it steepens, then drops down its face and rides the moving slope, spending a few seconds inside energy that the wind spent days pouring into the sea.",
    "Traditional archery is a study in stillness. The archer draws the string to an anchor point beside the face, holds the whole tension of the bow in the back muscles, and lets the arrow leave almost by surprise.\n\nGripping or flinching at the release sends the shot wide, so the discipline is to relax at the very moment of greatest strain, aiming less with the eye than with a trained body that has repeated the motion ten thousand times.",

    # --- light & sky phenomena ---
    "Lightning is the sky equalising a charge it can no longer hold. Colliding ice inside a storm cloud separates positive and negative until the voltage tears a conducting path through the air in stuttering steps.\n\nWhen the channel connects to the ground, a surge of current heats the air to five times the sun's surface in a flash, and the air explodes outward so fast that the shockwave reaches us, stretched by distance, as a roll of thunder.",
    "A rainbow is sunlight taken apart by rain. Each droplet acts as a tiny prism, bending the white light, bouncing it off the back of the drop, and splitting it into its colours as it exits.\n\nBecause every colour leaves at its own fixed angle, you only ever see the bow at a certain distance from the shadow of your own head, which means no two people share exactly the same rainbow, and you can never reach its end.",
    "Bioluminescence is life making its own light through chemistry rather than heat. A molecule called luciferin reacts with oxygen and gives off a cold glow that wastes almost none of its energy as warmth.\n\nIn the deep sea, where sunlight never reaches, most creatures can produce it, using flashes to lure prey, startle predators, or signal a mate in the dark, so the abyss is quietly stitched with living sparks.",
    "A snowflake is a diary of the air it fell through. Water vapour freezes onto a speck of dust and grows a six-sided crystal, its arms branching according to the temperature and humidity at each moment of its descent.\n\nBecause every flake takes a slightly different path down through the cloud, no two grow quite alike, yet all obey the same sixfold symmetry set by the way water molecules lock together as they freeze.",

    # --- knowledge & making ---
    "Old maps are arguments about the world as much as pictures of it. Before satellites, a cartographer stitched together sailors' logs, travellers' tales, and guesswork, filling the unknown interior with mountains, monsters, and hope.\n\nEvery projection lies in its own way, because a round earth cannot be flattened without stretching something, so the mapmaker chooses which truth to keep, and a map of the world is always also a map of what its makers cared about.",
    "The mechanical clock reorganised human life around a machine's steady beat. A falling weight drove a train of gears, and the crucial trick was the escapement, a rocking catch that released the gears one measured tick at a time.\n\nBefore it, time was the sun and the season; after it, monasteries, then towns, then whole economies ran to the striking of a bell, and punctuality became a virtue only because a device had made the hour a thing you could keep.",
    "A bonsai is a full-sized tree persuaded to live in miniature. By pruning the roots and shoots, wiring the branches, and rationing the soil, a grower holds a pine or maple to the height of a hand for decades.\n\nThe aim is not distortion but the illusion of great age and windswept survival, so the finest specimens, passed down through generations, look like ancient trees glimpsed from far off and shrunk without losing a single year of their dignity.",
    "Perfume is composed like music, in notes that reveal themselves over time. The top notes flash bright and vanish within minutes; the heart unfolds over an hour; the base of resins and musks clings to the skin for a day.\n\nA perfumer works from an organ of hundreds of essences, natural and synthetic, blending by memory toward an accord no single ingredient could give, so a good scent is not a smell but a small structured event that fades in a planned order.",
    "Whisky is patience aged in wood. A clear, fiery spirit distilled from fermented grain goes into a charred oak barrel almost flavourless, and the years do the rest, drawing colour and sweetness out of the wood.\n\nEach summer the spirit swells into the staves and each winter retreats, and a share evaporates away as the angels' share, so a decade in the barrel leaves less whisky but a rounder one, tasting of vanilla, smoke, and the cask that held it.",
    "Wine carries the memory of a place, what the French call terroir. The same grape grown on a chalk slope and on a gravel riverbank ripens into different wines, shaped by the soil, the angle of the sun, and the nightly chill.\n\nWinemakers argue endlessly over how much is the land and how much the hand, but a single hillside can be prized for centuries while the field next door is not, on the strength of what the roots find in the ground.",
]


def main():
    path = sys.argv[1]
    data = json.load(open(path))
    before = len(data)
    shutil.copy(path, path + ".bak")
    existing = {e["items"][0]["value"] for e in data}
    added = 0
    for para in NEW:
        if para in existing:
            continue
        data.append({"items": [{"value": para}]})
        added += 1
    json.dump(data, open(path, "w"), ensure_ascii=False, indent=2)
    print(f"topic bank: {before} -> {len(data)} (+{added} new); backup at {path}.bak")


if __name__ == "__main__":
    main()
